version: "2.4"

services:

  rss-to-telegram-bot:
    restart: "unless-stopped"
    build:
      context: .
    environment:
      # Timeout in seconds between requests to rss feed
      RSSREADER_TIMEOUT: 3600 # 1 hour
      # Path to RSS feed cache folder
      RSSREADER_CACHE_DIR: /app/cache
      # List of comma-separated URLs of RSS sources
      RSSREADER_SOURCES: https://portal1/news/rss/,https://portal2/rss/
      # If you want to show categories as hash-tags
      RSSREADER_SHOW_CATEGORIES_AS_TAGS: false
      # Telegram Channel Name
      TELEGRAM_CHANNEL_NAME: evilfreelancer
      # Telegram Access Token
      TELEGRAM_TOKEN: nnnnnnnnnnnnn:xxxXXXxXxXxXxXXxXxxXxxxxXx
    volumes:
      - ./bot_cache:/app/cache:rw
    logging:
      driver: "json-file"
      options:
        max-size: "50k"
